---
# ── ArgoCD Application : IoT Simulator ───────────────────────────────────────
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-simulator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/firas2004/pulsecity.git'
    targetRevision: HEAD
    path: k8s/iot-simulator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# ── ArgoCD Application : Anomaly Detector ─────────────────────────────────────
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anomaly-detector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/firas2004/pulsecity.git'
    targetRevision: HEAD
    path: k8s/anomaly-detector
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
